### ISSUE TITLE
[Bug] zk cannot query links of files in subdirectories

### ISSUE THREAD

**Issue by B4rc1** [mickael-menu/zk#170] opened 2022-02-21 11:42 UTC
```sh
$ zk init
$ zk new --title one
$ zk new --title two
$ mkdir my_dir
$ zk new --title three my_dir
```

After this you end up with a folder looking something like this:
```
❯ tree
 .
├──  my_dir
│  └──  5r1k.md
├──  1zyl.md
└──  koxo.md
```

Now insert links to file on in file two and three.

You should end up with:
```
❯ zk list
one 1zyl.md (3 minutes ago)


three my_dir/5r1k.md (3 minutes ago)

  ‣ [[1zyl]]

two koxo.md (3 minutes ago)

  ‣ [[1zyl]]


Found 3 notes
```

as you can see `two` and `three` link to `one`. When asking `zk` which file links to `one`:
```
❯ zk list --link-to 1zyl.md
two koxo.md (5 minutes ago)

  ‣ [[1zyl]]


Found 1 note
```

When asking which file `three` links:
```
❯ zk list --linked-by "my_dir/5r1k.md"

Found 0 note
```

**System Information**
zk version: [0.9.0](https://github.com/NixOS/nixpkgs/blob/d5f237872975e6fb6f76eef1368b5634ffcd266f/pkgs/applications/office/zk/default.nix#L5
)
```
❯ zk --version
zk dev
```

**Comment by mickael-menu** [comment] 2022-02-23 09:56
Thank you for the detailed bug report, I can reproduce it.

**Comment by j-hui** [comment] 2022-03-07 22:14
Probably related: zk also doesn't seem to count links from subdirectories when figuring out which notes are orphans.

```shell
$ zk init --no-input
$ zk new --title one # xu2y.md
$ mkdir my_dir && zk new --title two my_dir # he0x.md
```

Say I link these notes to each other:

```shell
$ zk list
one xu2y.md (3 minutes ago)

  ‣ [[my_dir/he0x]]

two my_dir/he0x.md (3 minutes ago)

  ‣ [[xu2y]]


Found 2 notes
```

Because these are linked circularly, neither should be considered an orphan. However:

```shell
$ zk list --orphan
one xu2y.md (4 minutes ago)

  ‣ [[my_dir/he0x]]


Found 1 note
```

one is still considered an orphan despite the link from two.

I post here because this seems like a different expression of the same issue, but I'm happy to open a new issue if that makes things easier to track.

**Comment by mickael-menu** [comment] 2022-03-20 13:37
@j-hui It's fine here, I'll check if the issues are related after fixing the first one.

**Comment by waynezhang** [comment] 2022-04-06 13:43
Coming from Logseq. I'm keeping journals in `journals` directory and other things in `pages` directory. But they can not refer to each others.

**Comment by dj8yfo** [comment] 2022-04-07 21:58
Bump. Seeing this too.

**Comment by mickael-menu** [comment] 2022-04-23 16:01
It should be fixed in `main` now, could someone confirm?

@j-hui Yes it was indeed the same issue.

**Closed** 2022-04-23 16:01 UTC
Labels: bug

**Comment by B4rc1** [comment] 2022-04-24 13:19
still present for me on commit 7622d9e:
```
❯ ./zk list technical-tests/linking2.md
linking2 technical-tests/linking2.md (3 months ago)

  ‣ [[references/lua]]


Found 1 note
```
```
❯ ./zk list --linked-by technical-tests/linking2.md

Found 0 note
```
```
❯ ./zk list --link-to references/lua.md

Found 0 note
```

**Comment by mickael-menu** [comment] 2022-04-24 14:01
@B4rc1 Your example works for me, make sure you are really using the latest version (check `zk --version` maybe).

Also forcing to reindex your notebook might help: `zk index --force`.

**Comment by B4rc1** [comment] 2022-04-24 14:04
reindexing (`zk index --force`) fixed it. There should be a disclaimer somewhere to reindex your notebook on updates (or do that automatically)

**Comment by mickael-menu** [comment] 2022-04-24 14:06
Yeah I think I'll add a reindexing step for the next release. Thanks for confirming the fix.
